name: Forest Tour Reminder

on:
  schedule:
    # Every 1.5 hours starting at 00:00 (5 minutes early, e.g. 00:00, 03:00, 06:00, ...)
    - cron: "0 0,3,6,9,12,15,18,21 * * *"
    # Every 1.5 hours starting at 01:30 (5 minutes early, e.g. 01:30, 04:30, 07:30, ...)
    - cron: "30 1,4,7,10,13,16,19,22 * * *"
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Reminder with Banner
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "content": "@everyone Reminder! Forest Tour will start soon!",
              "embeds": [
                {
                  "title": "Event Reminder",
                  "description": "Prepare for the upcoming event!",
                  "color": 16711680,
                  "image": {
                    "url": "https://dmowiki.com/images/a/a4/Loading_ForestArea.jpg"
                  },
                  "footer": {
                    "text": "Next event soon..."
                  }
                }
              ]
            }' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
