name: Discord 90-Minute Reminder (5 Minutes Early)

on:
  schedule:
    # For 5 minutes before spawn times in GMT+7
    # Subtract 7 hours from your desired local times
    - cron: "55 16,19,22,1,4,7,10,13 * * *" # 23:55, 02:55, 05:55, 08:55, 11:55, 14:55, 17:55, 20:55 GMT+7
    - cron: "25 18,21,0,3,6,9,12,15 * * *" # 01:25, 04:25, 07:25, 10:25, 13:25, 16:25, 19:25, 22:25 GMT+7
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Reminder with Banner
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "content": "@everyone Apocalymon will spawn in soon!",
              "embeds": [
                {
                  "title": "☠️ APOCALYMON SPAWNED",
                  "description": "Prepare for battle! A wild Apocalymon has emerged in the Digital World!",
                  "color": 16711680,
                  "image": {
                    "url": "https://dmowiki.com/images/a/a0/Apocalymon.png"
                  },
                  "footer": {
                    "text": "Next spawn in 90 minutes..."
                  }
                }
              ]
            }' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
