name: Discord 90-Minute Reminder (5 Minutes Early)

on:
  schedule:
    - cron: "55 23,2,5,8,11,14,17,20 * * *" # 23:55, 02:55, 05:55, ...
    - cron: "25 1,4,7,10,13,16,19,22 * * *" # 01:25, 04:25, 07:25, ...
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Reminder with Banner
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "content": "@everyone Apocalymon will spawn in 5 minutes! Get ready to battle!",
              "embeds": [
                {
                  "title": "☠️ APOCALYMON SPAWNED",
                  "description": "Prepare for battle! A wild Apocalymon has emerged in the Digital World!",
                  "color": 16711680,
                  "image": {
                    "url": "https://dmowiki.com/images/a/a0/Apocalymon.png"
                  },
                  "footer": {
                    "text": "Next spawn in 90 minutes..."
                  }
                }
              ]
            }' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
