name: Forest Tour Reminder

on:
  schedule:
    # Every 1.5 hours starting at 00:05 (e.g. 00:05, 01:35, 03:05, ...)
    - cron: "5 0,1,3,4,6,7,9,10,12,13,15,16,18,19,21,22 * * *"
    # Every 1.5 hours starting at 01:35 (e.g. 01:35, 03:05, 04:35, ...)
    - cron: "35 1,2,4,5,7,8,10,11,13,14,16,17,19,20,22,23 * * *"
  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Reminder with Banner
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{
              "content": "@everyone Reminder! Forest Tour will start soon!",
              "embeds": [
                {
                  "title": "Event Reminder",
                  "description": "Prepare for the upcoming event!",
                  "color": 16711680,
                  "footer": {
                    "text": "Next event in 5 minutes..."
                  }
                }
              ]
            }' \
            "${{ secrets.DISCORD_WEBHOOK_URL }}"
